Add contact info
BHObserver/portfolio pull request #3
Opened 2023-06-13 10:36 UTC by BHObserver

Implemented a new feature to the website.

- Created a new section for contact.
- Created a form to get user data for the contact.

2023-06-13 11:35 UTC, frank1738 reviewed
Hi @BHObserver , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request



- [ ] Most sections of your readme file are empty. Kindly customize them with the relevant project details. This will make your work more professional

![image](https://github.com/BHObserver/portfolio/assets/98453979/79b077f2-2a86-4cc3-bedf-c42ce0691a1e)
![image](https://github.com/BHObserver/portfolio/assets/98453979/2c791d4f-34d7-42f9-9977-ecc825fdd299)



Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2023-06-13 12:23 UTC, AbelG101 reviewed
![](https://media.giphy.com/media/PkFYci8BUkmdA7K1qa/giphy.gif)

# Hi @BHObserver  👋, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

- Please take note that this is a pair-programming activity which means each team member needs to have a substantial contribution to the project. So please reach out to your team members and have them add some commits.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2023-06-13 16:33 UTC, joskalenda requested changes
| STATUS: REQUIRED CHANGES ♻️  |
|--------------------------------|
| Hi @BHObserver , |
|Good job so far! There are some issues that you still need to work on to go to the next project but you are almost there! |
| <img src="https://media2.giphy.com/media/gPdC6JQLdJxP9dy3A8/giphy-downsized-medium.gif"/> |

## Highlights

- [ ].. ✅ Great design
- [ ].. ✅ Clean code
- [ ].. ✅ Good readme file

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

-------
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me(@joskalenda) in your question so I can receive the notification.

> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-13 16:33 UTC, joskalenda commented on index.html
> +                <button type="button" class="get-in-touch-btn" name="get-in-touch" id="">Get in touch</button>
- [ ] Well done but we have a few points to add before all, you are missing the `formspree` config in your form action
- [ ] All your input files and text area should have a `required` attribute
- [ ] The full name should have a `maxlength="30"` attribute
- [ ] Your text area should have the `maxlength="500"` attribute.
- Please make an effort to adjust your left padding on the placeholder as shown below
<img width="309" alt="1" src="https://github.com/BHObserver/portfolio/assets/77843050/6c4ff8b8-9e04-4407-bc98-163e66d92c38">

FIGMA
<img width="320" alt="2" src="https://github.com/BHObserver/portfolio/assets/77843050/6566b3a9-6fc3-4d1f-a116-590046917dfb">

- [ ] Your button should have `submit` type, not button

2023-06-13 18:50 UTC, Kamba56 requested changes
Hi @BHObserver, 

Great work on making the changes requested by a previous reviewer 👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
- [x] Great job using flexbox and grid to style contents!👏👏👏
- [x] Great job adding contact srection!👏👏👏

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-13 18:50 UTC, Kamba56 commented on index.html
> +                <textarea type="text" name="message" class="textarea" maxlength="500" placeholder="Hey I'd like to connect too"></textarea>
- [ ] As suggested by previous reviewer, all input fields should be required. Kindly add a required attribute to the textarea.

2023-06-13 18:50 UTC, Kamba56 commented on index.html
> +            <form action="" class="form" action="https://formspree.io/f/mwkjgvpr"
- [ ] Great job adding formspree. But when I try submitting the form, I get an error. Kindly make sure your link is correct.
![image](https://github.com/BHObserver/portfolio/assets/94551484/c15060cb-f4aa-4ffa-b1d0-5188ce9a6126)

2023-06-13 20:39 UTC, Ofarouq310 requested changes
Hi @BHObserver, ✋  

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet. 🥈

![giphy](https://github.com/BHObserver/portfolio/assets/102612396/200fb9b5-0ac4-43ee-aeef-abb34d0c7927)

 ## Highlights
✅ Followed GitHub flow.
✅ Descriptive PR title.
✅ Good README file.


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-13 20:39 UTC, Ofarouq310 commented on index.html
> +            method="POST">
- [ ] Kindly note that because you are providing two `action` attributes, your data are not collected, thus we get this error page, kindly remove the empty `action` attribute.
```suggestion
            <form class="form" action="https://formspree.io/f/mwkjgvpr"
            method="POST">
```
  
 ![image](https://github.com/BHObserver/portfolio/assets/102612396/3a3908b6-a063-4197-b85c-fcb64638a033)

2023-06-13 20:39 UTC, Ofarouq310 commented on index.html
> +                <button type="submit" class="get-in-touch-btn" name="get-in-touch" id="">Get in touch</button>
[OPTIONAL]
- [ ] I recommend you follow the design guidelines and implement the button interactions required for the best user experience possible.
  
  ![image](https://github.com/BHObserver/portfolio/assets/102612396/d5e10f60-db92-4036-a113-76dbbc754c19)

2023-06-14 02:19 UTC, Cabraham1 approved these changes
Hi @BHObserver  , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media1.giphy.com/media/3kuSo744UIPJjcJUEn/giphy.gif"/>

## Highlights
📌 Descriptive pull request✅
📌 Good commit messages ✅
📌 Professional README file ✅

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-14 02:34 UTC, merged